# Generated by Django 5.2.11 on 2026-02-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('discapacidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('letra', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('DESHABILITADO', 'Deshabilitado')], default='ACTIVO', max_length=20)),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atencionapp.moduloatencion')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('EN_ATENCION', 'En atención'), ('ATENDIDO', 'Atendido')], default='EN_COLA', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='atencionapp.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='atencionapp.funcionario')),
                ('tipo_atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='atencionapp.tipoatencion')),
            ],
        ),
    ]
